### ISSUE TITLE
Compilation flags for SIMD

### ISSUE THREAD

**Issue by mahoon2** [SNU-ARC/2023_fall_comarch_PA5#1]
![image](https://github.com/SNU-ARC/2023_fall_comarch_PA5/assets/2969317/beb23122-f7ca-4d60-bc7d-5a9edb260068)

SIMD를 사용하기 위해 additional compilation flag인
`#pragma GCC target ("avx,avx2")`
전처리기를 사용하였습니다.

이것이 혹시 문제가 되진 않을까요?
감사합니다.

**Comment by jeonghonoh** [comment]
저도 SIMD를 사용하기 위해 `#pragma GCC target("avx2,fma")`를 사용하였습니다.
과제 제한 범위를 벗어나지 않은 것인지 궁금합니다.

감사합니다.

**Comment by 99DHL** [comment]
네 SIMD operation을 사용한다는 가정하에 avx, avx2, fma는 사용해도 됩니다.
리포트에 해당 사실을 포함해주시기 바랍니다.
감사합니다.
