### ISSUE TITLE
input.txt

### ISSUE THREAD

**Issue by gse1818** [SNU-ARC/2023_fall_comarch_PA5#4]
안녕하세요, 항상 고생 많으십니다.

테스트 시에 주어지는 input.txt에 음수가 없음을 가정해도 될까요?

**Comment by 99DHL** [comment]
안녕하세요.
음수인 input에 대해서도 코드가 잘 동작해야 합니다.
음수 뿐만 아니라 int datatype으로 표현할 수 있는 모든 input에 대해 잘 동작해야 합니다.
예를 들어, input을 short, int8등 더 적은 메모리를 요구하는 datatype으로 바꿔서 처리하는 등의 최적화는 허용되지 않습니다.
